name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true

    - name: Run Tests
      run: go test -v ./...

    - name: Verify Installation
      run: |
        # Try to install the package
        go install
        
        # Verify the binary exists and can run
        # This assumes your module name matches the binary name
        $HOME/go/bin/$(basename $(pwd)) -h || true 